# Generated by Django 5.0 on 2024-01-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_claimquerymodel_service_final_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimquerymodel',
            name='service_accidentLoc',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimquerymodel',
            name='service_name',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimquerymodel',
            name='service_policy',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
