# Generated by Django 5.0 on 2024-01-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_claimquerymodel_service_accidentloc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimquerymodel',
            name='service_police_report',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
